<?php

namespace App\Http\Requests\Planejamento;

use Illuminate\Foundation\Http\FormRequest;

class PlanejamentoFormRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'titulo' => 'required',
            'descricao' => 'required',
            'data_entrega' => 'required',
            'responsavel' => 'required',
            'planejamento_categoria' => 'requried|numeric',
        ];
    }

    public function messages()
    {
        return [
            'titulo.required' => 'O campo é de preenchimento obrigatório.',
            'descricao.required' => 'O campo é de preenchimento obrigatório.',
            'data_entrega.required' => 'O campo é de preenchimento obrigatório.',
            'responsavel.required' => 'O campo é de preenchimento obrigatório.',
            'planejamento_categoria.required' => 'O campo é de preenchimento obrigatório.',
            'planejamento_categoria.numeric' => 'O campo só aceita informações númericas.',
        ]; // TODO: Change the autogenerated stub
    }
}
