<?php

namespace App\Http\Requests\Noticias;

use Illuminate\Foundation\Http\FormRequest;

class NoticiasFormRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'titulo' => 'required',
            'conteudo' => 'required',
        ];
    }

    public function messages()
    {
        return [
            'titulo.required' => 'O campo título é de preenchimento obrigatório.',
            'conteudo.required' => 'O campo conteúdo é de preenchimento obrigatório.',
        ]; // TODO: Change the autogenerated stub
    }
}
