<?php

use Illuminate\Database\Seeder;
use App\Model\Sistemas_Webpublico;

class SistemaWebPublicoTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        Sistemas_Webpublico::create([
            'num_usuarios' => 2000,
            'num_linhas_codigo' => 2011542,
            'num_modulos' => 45,
            'num_telas' => 3636,
            'num_tabelas' => 4313,
            'num_horas' => 160,
            'ch_recursos_humanos' => 0,
            'ch_administrativo' =>  0,
            'ch_contabil' => 0,
            'ch_transporte' => 0,
            'ch_portais' => 0,
            'ch_previdenciario' => 0,
            'ch_tributario' => 0,
            'criado_por' => 1,
            'num_areas_gestao' => 0,
            'hr_recursos_humanos' => 0,
            'hr_administrativo' => 0,
            'hr_contabil' => 0,
            'hr_transporte' => 0,
            'hr_portais' => 0,
            'hr_previdenciario' => 0,
            'hr_tributario' => 0
        ]);

        Sistemas_Webpublico::create([
            'num_usuarios' => 2011542,
            'num_linhas_codigo' => 0,
            'num_modulos' => 45,
            'num_telas' => 3636,
            'num_tabelas' => 4313,
            'num_horas' => 160,
            'ch_recursos_humanos' => 0,
            'ch_administrativo' =>  0,
            'ch_contabil' => 0,
            'ch_transporte' => 0,
            'ch_portais' => 0,
            'ch_previdenciario' => 0,
            'ch_tributario' => 0,
            'criado_por' => 1,
            'num_areas_gestao' => 0,
            'hr_recursos_humanos' => 0,
            'hr_administrativo' => 0,
            'hr_contabil' => 0,
            'hr_transporte' => 0,
            'hr_portais' => 0,
            'hr_previdenciario' => 0,
            'hr_tributario' => 0
        ]);
        Sistemas_Webpublico::create([
            'num_usuarios' => 2011542,
            'num_linhas_codigo' => 0,
            'num_modulos' => 45,
            'num_telas' => 3636,
            'num_tabelas' => 4313,
            'num_horas' => 160,
            'ch_recursos_humanos' => 0,
            'ch_administrativo' =>  0,
            'ch_contabil' => 0,
            'ch_transporte' => 0,
            'ch_portais' => 0,
            'ch_previdenciario' => 0,
            'ch_tributario' => 0,
            'criado_por' => 1,
            'num_areas_gestao' => 0,
            'hr_recursos_humanos' => 0,
            'hr_administrativo' => 0,
            'hr_contabil' => 0,
            'hr_transporte' => 0,
            'hr_portais' => 0,
            'hr_previdenciario' => 0,
            'hr_tributario' => 0
        ]);

        Sistemas_Webpublico::create([
            'num_usuarios' => 2000,
            'num_linhas_codigo' => 2011542,
            'num_modulos' => 45,
            'num_telas' => 3636,
            'num_tabelas' => 4313,
            'num_horas' => 160,
            'ch_recursos_humanos' => 0,
            'ch_administrativo' =>  0,
            'ch_contabil' => 0,
            'ch_transporte' => 0,
            'ch_portais' => 0,
            'ch_previdenciario' => 0,
            'ch_tributario' => 0,
            'criado_por' => 1,
            'num_areas_gestao' => 0,
            'hr_recursos_humanos' => 0,
            'hr_administrativo' => 0,
            'hr_contabil' => 0,
            'hr_transporte' => 0,
            'hr_portais' => 0,
            'hr_previdenciario' => 0,
            'hr_tributario' => 0
        ]);

        Sistemas_Webpublico::create([
            'num_usuarios' => 2001,
            'num_linhas_codigo' => 2011542,
            'num_modulos' => 45,
            'num_telas' => 3636,
            'num_tabelas' => 4313,
            'num_horas' => 160,
            'ch_recursos_humanos' => 0,
            'ch_administrativo' =>  0,
            'ch_contabil' => 0,
            'ch_transporte' => 0,
            'ch_portais' => 0,
            'ch_previdenciario' => 0,
            'ch_tributario' => 0,
            'criado_por' => 1,
            'num_areas_gestao' => 0,
            'hr_recursos_humanos' => 0,
            'hr_administrativo' => 0,
            'hr_contabil' => 0,
            'hr_transporte' => 0,
            'hr_portais' => 0,
            'hr_previdenciario' => 0,
            'hr_tributario' => 0
        ]);

        Sistemas_Webpublico::create([
            'num_usuarios' => 2003,
            'num_linhas_codigo' => 2011542,
            'num_modulos' => 45,
            'num_telas' => 3636,
            'num_tabelas' => 4313,
            'num_horas' => 160,
            'ch_recursos_humanos' => 0,
            'ch_administrativo' =>  0,
            'ch_contabil' => 0,
            'ch_transporte' => 0,
            'ch_portais' => 0,
            'ch_previdenciario' => 0,
            'ch_tributario' => 0,
            'criado_por' => 1,
            'num_areas_gestao' => 0,
            'hr_recursos_humanos' => 0,
            'hr_administrativo' => 0,
            'hr_contabil' => 0,
            'hr_transporte' => 0,
            'hr_portais' => 0,
            'hr_previdenciario' => 0,
            'hr_tributario' => 0
        ]);

        Sistemas_Webpublico::create([
            'num_usuarios' => 2003,
            'num_linhas_codigo' => 2011542,
            'num_modulos' => 45,
            'num_telas' => 3636,
            'num_tabelas' => 4313,
            'num_horas' => 160,
            'ch_recursos_humanos' => 0,
            'ch_administrativo' =>  0,
            'ch_contabil' => 0,
            'ch_transporte' => 0,
            'ch_portais' => 0,
            'ch_previdenciario' => 0,
            'ch_tributario' => 0,
            'criado_por' => 1,
            'num_areas_gestao' => 0,
            'hr_recursos_humanos' => 0,
            'hr_administrativo' => 0,
            'hr_contabil' => 0,
            'hr_transporte' => 0,
            'hr_portais' => 0,
            'hr_previdenciario' => 0,
            'hr_tributario' => 0
        ]);

        Sistemas_Webpublico::create([
            'num_usuarios' => 2003,
            'num_linhas_codigo' => 2011542,
            'num_modulos' => 45,
            'num_telas' => 3636,
            'num_tabelas' => 4313,
            'num_horas' => 160,
            'ch_recursos_humanos' => 0,
            'ch_administrativo' =>  0,
            'ch_contabil' => 0,
            'ch_transporte' => 0,
            'ch_portais' => 0,
            'ch_previdenciario' => 0,
            'ch_tributario' => 0,
            'criado_por' => 1,
            'num_areas_gestao' => 0,
            'hr_recursos_humanos' => 0,
            'hr_administrativo' => 0,
            'hr_contabil' => 0,
            'hr_transporte' => 0,
            'hr_portais' => 0,
            'hr_previdenciario' => 0,
            'hr_tributario' => 0
        ]);

        Sistemas_Webpublico::create([
            'num_usuarios' => 2003,
            'num_linhas_codigo' => 2011542,
            'num_modulos' => 45,
            'num_telas' => 3636,
            'num_tabelas' => 4313,
            'num_horas' => 160,
            'ch_recursos_humanos' => 471,
            'ch_administrativo' =>  442,
            'ch_contabil' => 518,
            'ch_transporte' => 44,
            'ch_portais' => 42,
            'ch_previdenciario' => 1,
            'ch_tributario' => 213,
            'criado_por' => 1,
            'num_areas_gestao' => 0,
            'hr_recursos_humanos' => 0,
            'hr_administrativo' => 0,
            'hr_contabil' => 0,
            'hr_transporte' => 0,
            'hr_portais' => 0,
            'hr_previdenciario' => 0,
            'hr_tributario' => 0
        ]);

        Sistemas_Webpublico::create([
            'num_usuarios' => 2003,
            'num_linhas_codigo' => 2011542,
            'num_modulos' => 45,
            'num_telas' => 3636,
            'num_tabelas' => 4313,
            'num_horas' => 160,
            'ch_recursos_humanos' => 471,
            'ch_administrativo' =>  442,
            'ch_contabil' => 518,
            'ch_transporte' => 44,
            'ch_portais' => 42,
            'ch_previdenciario' => 1,
            'ch_tributario' => 213,
            'criado_por' => 1,
            'num_areas_gestao' => 0,
            'hr_recursos_humanos' => 0,
            'hr_administrativo' => 0,
            'hr_contabil' => 0,
            'hr_transporte' => 0,
            'hr_portais' => 0,
            'hr_previdenciario' => 0,
            'hr_tributario' => 0
        ]);

        Sistemas_Webpublico::create([
            'num_usuarios' => 2003,
            'num_linhas_codigo' => 2011542,
            'num_modulos' => 45,
            'num_telas' => 3636,
            'num_tabelas' => 4313,
            'num_horas' => 160,
            'ch_recursos_humanos' => 471,
            'ch_administrativo' =>  442,
            'ch_contabil' => 518,
            'ch_transporte' => 44,
            'ch_portais' => 42,
            'ch_previdenciario' => 1,
            'ch_tributario' => 213,
            'criado_por' => 1,
            'num_areas_gestao' => 7,
            'hr_recursos_humanos' => 0,
            'hr_administrativo' => 0,
            'hr_contabil' => 0,
            'hr_transporte' => 0,
            'hr_portais' => 0,
            'hr_previdenciario' => 0,
            'hr_tributario' => 0
        ]);

        Sistemas_Webpublico::create([
            'num_usuarios' => 2003,
            'num_linhas_codigo' => 2011542,
            'num_modulos' => 45,
            'num_telas' => 3636,
            'num_tabelas' => 4313,
            'num_horas' => 160,
            'ch_recursos_humanos' => 471,
            'ch_administrativo' =>  442,
            'ch_contabil' => 518,
            'ch_transporte' => 44,
            'ch_portais' => 42,
            'ch_previdenciario' => 1,
            'ch_tributario' => 213,
            'criado_por' => 1,
            'num_areas_gestao' => 7,
            'hr_recursos_humanos' => 0,
            'hr_administrativo' => 0,
            'hr_contabil' => 0,
            'hr_transporte' => 0,
            'hr_portais' => 0,
            'hr_previdenciario' => 0,
            'hr_tributario' => 0
        ]);

        Sistemas_Webpublico::create([
            'num_usuarios' => 2003,
            'num_linhas_codigo' => 2011542,
            'num_modulos' => 45,
            'num_telas' => 3636,
            'num_tabelas' => 4313,
            'num_horas' => 160,
            'ch_recursos_humanos' => 471,
            'ch_administrativo' =>  442,
            'ch_contabil' => 518,
            'ch_transporte' => 44,
            'ch_portais' => 42,
            'ch_previdenciario' => 1,
            'ch_tributario' => 213,
            'criado_por' => 1,
            'num_areas_gestao' => 7,
            'hr_recursos_humanos' => 1,
            'hr_administrativo' => 0,
            'hr_contabil' => 0,
            'hr_transporte' => 0,
            'hr_portais' => 0,
            'hr_previdenciario' => 0,
            'hr_tributario' => 0
        ]);

        Sistemas_Webpublico::create([
            'num_usuarios' => 2003,
            'num_linhas_codigo' => 2011542,
            'num_modulos' => 45,
            'num_telas' => 3636,
            'num_tabelas' => 4313,
            'num_horas' => 160,
            'ch_recursos_humanos' => 471,
            'ch_administrativo' =>  442,
            'ch_contabil' => 518,
            'ch_transporte' => 44,
            'ch_portais' => 42,
            'ch_previdenciario' => 1,
            'ch_tributario' => 213,
            'criado_por' => 1,
            'num_areas_gestao' => 7,
            'hr_recursos_humanos' => 1,
            'hr_administrativo' => 0,
            'hr_contabil' => 0,
            'hr_transporte' => 0,
            'hr_portais' => 0,
            'hr_previdenciario' => 0,
            'hr_tributario' => 0
        ]);

        Sistemas_Webpublico::create([
            'num_usuarios' => 2003,
            'num_linhas_codigo' => 2011542,
            'num_modulos' => 45,
            'num_telas' => 3636,
            'num_tabelas' => 4313,
            'num_horas' => 160,
            'ch_recursos_humanos' => 471,
            'ch_administrativo' =>  442,
            'ch_contabil' => 518,
            'ch_transporte' => 44,
            'ch_portais' => 42,
            'ch_previdenciario' => 1,
            'ch_tributario' => 213,
            'criado_por' => 1,
            'num_areas_gestao' => 7,
            'hr_recursos_humanos' => 1,
            'hr_administrativo' => 2,
            'hr_contabil' => 3,
            'hr_transporte' => 4,
            'hr_portais' => 5,
            'hr_previdenciario' => 6,
            'hr_tributario' => 7
        ]);

        Sistemas_Webpublico::create([
            'num_usuarios' => 2003,
            'num_linhas_codigo' => 2011542,
            'num_modulos' => 45,
            'num_telas' => 3636,
            'num_tabelas' => 4313,
            'num_horas' => 160,
            'ch_recursos_humanos' => 471,
            'ch_administrativo' =>  442,
            'ch_contabil' => 518,
            'ch_transporte' => 44,
            'ch_portais' => 42,
            'ch_previdenciario' => 1,
            'ch_tributario' => 213,
            'criado_por' => 1,
            'num_areas_gestao' => 7,
            'hr_recursos_humanos' => 1,
            'hr_administrativo' => 2,
            'hr_contabil' => 3,
            'hr_transporte' => 4,
            'hr_portais' => 5,
            'hr_previdenciario' => 6,
            'hr_tributario' => 7
        ]);

        Sistemas_Webpublico::create([
            'num_usuarios' => 2003,
            'num_linhas_codigo' => 2011542,
            'num_modulos' => 45,
            'num_telas' => 3636,
            'num_tabelas' => 4313,
            'num_horas' => 160,
            'ch_recursos_humanos' => 471,
            'ch_administrativo' =>  442,
            'ch_contabil' => 518,
            'ch_transporte' => 44,
            'ch_portais' => 42,
            'ch_previdenciario' => 1,
            'ch_tributario' => 213,
            'criado_por' => 1,
            'num_areas_gestao' => 7,
            'hr_recursos_humanos' => 1,
            'hr_administrativo' => 2,
            'hr_contabil' => 3,
            'hr_transporte' => 4,
            'hr_portais' => 5,
            'hr_previdenciario' => 6,
            'hr_tributario' => 7
        ]);
    }
}
