<?php

namespace App\Http\Requests\Infraestrutura;

use Illuminate\Foundation\Http\FormRequest;

class InfraestruturaConfigFormRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'media_chamados_fibra' => 'required|numeric',
            'media_chamados_cidade_digital' => 'required|numeric',
            'num_switch' => 'required|numeric',
            'num_servidores_virtuais' => 'required|numeric',
            'num_servidores_fisicos' => 'required|numeric',
            'num_usuarios_internet' => 'required|numeric',
            'num_email_corp' => 'required|numeric',
            'media_ataques' => 'required|numeric',
            'num_usuarios_internet_social' => 'required|numeric',
            'media_internet_social_dia' => 'required|numeric',
            'num_conexao_fibra' => 'required|numeric',
            'num_conexao_radio' => 'required|numeric',
        ];
    }

    public function messages()
    {
        return [
            'media_chamados_fibra.required' => 'O campo é de preenchimento obrigatório.',
            'media_chamados_cidade_digital.required' => 'O campo é de preenchimento obrigatório.',
            'num_switch.required' => 'O campo é de preenchimento obrigatório.',
            'num_servidores_virtuais.required' => 'O campo é de preenchimento obrigatório.',
            'num_servidores_fisicos.required' => 'O campo é de preenchimento obrigatório.',
            'num_usuarios_internet.required' => 'O campo é de preenchimento obrigatório.',
            'num_email_corp.required' => 'O campo é de preenchimento obrigatório.',
            'media_ataques.required' => 'O campo é de preenchimento obrigatório.',
            'num_usuarios_internet_social.required' => 'O campo é de preenchimento obrigatório.',
            'media_internet_social_dia.required' => 'O campo é de preenchimento obrigatório.',
            'num_conexao_fibra.required' => 'O campo é de preenchimento obrigatório.',
            'num_conexao_radio.required' => 'O campo é de preenchimento obrigatório.',

            'media_chamados_fibra.numeric' => 'O campo só aceita informações númericas.',
            'media_chamados_cidade_digital.numeric' => 'O campo só aceita informações númericas.',
            'num_switch.numeric' => 'O campo só aceita informações númericas.',
            'num_servidores_virtuais.numeric' => 'O campo só aceita informações númericas.',
            'num_servidores_fisicos.numeric' => 'O campo só aceita informações númericas.',
            'num_usuarios_internet' => 'O campo só aceita informações númericas.',
            'num_email_corp.numeric' => 'O campo só aceita informações númericas.',
            'media_ataques.numeric' => 'O campo só aceita informações númericas.',
            'num_usuarios_internet_social.numeric' => 'O campo só aceita informações númericas.',
            'media_internet_social_dia.numeric' => 'O campo só aceita informações númericas.',
            'num_conexao_fibra.numeric' => 'O campo só aceita informações númericas.',
            'num_conexao_radio.numeric' => 'O campo só aceita informações númericas.',
        ]; // TODO: Change the autogenerated stub
    }
}
