<?php

namespace App\Http\Requests\Infraestrutura;

use Illuminate\Foundation\Http\FormRequest;

class InfraestruturaFormRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'titulo' => 'required',
            'quilometragem' => 'required',
            'ano' => 'required|numeric',
            'cor' => 'required',
        ];
    }

    public function messages()
    {
        return [
            'titulo.required' => 'O campo título é de preenchimento obrigatório.',
            'quilometragem.required' => 'O campo quantidade é de preenchimento obrigátorio.',
            'ano.required' => 'O campo ano é de preenchimento obrigatório',
            'ano.numeric' => 'O campo ano só aceitar informações númericas.',
            'cor.requried' => 'O campo cor é de preenchimento obrigatório.',
        ]; // TODO: Change the autogenerated stub
    }
}
