<?php

namespace App\Http\Requests\Documentos;

use Illuminate\Foundation\Http\FormRequest;

class DocumentosFormRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'documentos_categorias_id' => 'required|numeric',
            'titulo' => 'required',
            'descricao' => 'required',
            'valor' => 'required',
            'data_inicio' => 'required|date',
            'data_fim' => 'required|date',
            'arquivo_documento' => 'required',
        ];
    }

    public function messages()
    {
        return [
            'documentos_categorias_id.required' => 'o campo é de preenchimento obrigatório.',
            'titulo.required' => 'o campo é de preenchimento obrigatório.',
            'descricao.required' => 'o campo é de preenchimento obrigatório.',
            'valor.required' => 'o campo é de preenchimento obrigatório.',
            'data_inicio.required' => 'o campo é de preenchimento obrigatório.',
            'data_fim.required' => 'o campo é de preenchimento obrigatório.',
            'arquivo_documento.required' => 'o campo é de preenchimento obrigatório.',
            'documentos_categorias_id.numeric' => 'O campo só aceita informações númericas.',
            'data_inicio.date' => 'O campo precisa se no formato de uma data.',
            'data_fim.date' => 'O campo precisa se no formato de uma data.',
        ]; // TODO: Change the autogenerated stub
    }
}
